# Generated by Django 5.0.4 on 2024-04-21 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0003_streamingplatforms_watchlist_delete_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='platform',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to='watchlist.streamingplatforms'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streamingplatforms',
            name='website',
            field=models.URLField(max_length=100),
        ),
    ]
